### ISSUE TITLE
Intel HD 4600 doesn't work

### ISSUE THREAD

**Issue by scottpipia** [Nishit-Chauhan/Ventura-Hackintosh-Haswell-EFI#2]
Intel Core i5-4460 Processor
Intel HD 4600
OpenCore 0.8.5

The Graphic driver doesn't work. Can you guide me on how to fix it?

**Comment by Nishit-Chauhan** [comment]
Hello @scottpipia 
you just need to use OCLP to patch the intel HD 4600 graphics.
