### ISSUE TITLE
Can I use the EFI with i5 4570.

### ISSUE THREAD

**Issue by qaisarehman** [Nishit-Chauhan/Ventura-Hackintosh-Haswell-EFI#3]
Please Can i use this with i5 4570? Im unable to get the iGPU working its hd 4600, everytime i patch the GPU, after restart its stuck on IOConsoleUsers: gIOScreenLockState 3

My monitor is on DVI.

**Comment by Nishit-Chauhan** [comment]
@qaisarehman Yes you can use this, but not sure about DVI support. mine is working with HDMI.
