### ISSUE TITLE
GPU recognized but without Hardware acceleration

### ISSUE THREAD

**Issue by zhangry868** [Nishit-Chauhan/Ventura-Hackintosh-Haswell-EFI#4]
Nice to see your sharing! After applying OCLP, HD 4600 got recognized. After borrowing some items from you config.list, I can get the correct resolution. However, the hardware acceleration is still not available (no transparency on the Docker, etc).

I am using Intel Core i7 4790 with HD 4600. Any idea and advice is welcome!

Thanks a lot :)

**Comment by Nishit-Chauhan** [comment]
@zhangry868 double check if there is device-id added in your config.plist, if it is there please remove the device id and try OCLP to apply the graphics fix patch.
